client_id = "85d36c2bc325efc60deb33dd709aee20"
name = "camero-testing"
application_url = "https://camero.myabmedia.com"        # your live app URL
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"    # use a stable API version your code targets

# subscribe to mandatory compliance webhooks
[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://camero.myabmedia.com/api/shopify/webhooks"   # single endpoint root for compliance

[access_scopes]
scopes = "read_products,write_products,read_orders,read_customers"  # required scopes

[auth]
redirect_urls = [ "https://camero.myabmedia.com/api/shopify/callback" ]
